[package]
name = "webas"
version = "0.1.0"
edition = "2024"

[dependencies]
fs_extra = "1.3.0"
pulldown-cmark = "0.12.2"
regex = "1.11.1"
serde = {version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
tera = "1.20.0"
